apiVersion: v1
kind: Pod
metadata:
  name: spark-driver-template
spec:
  serviceAccountName: spark-driver
  containers:
    - name: spark-kubernetes-driver
      env:
        - name: PYTHONPATH
          valueFrom:
            configMapKeyRef:
              name: spark-job-config
              key: PYTHONPATH

        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: spark-job-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: spark-job-config
              key: POSTGRES_PORT
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: spark-job-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: spark-job-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: spark-job-secrets
              key: POSTGRES_PASSWORD

        - name: CLICKHOUSE_HOST
          valueFrom:
            configMapKeyRef:
              name: spark-job-config
              key: CLICKHOUSE_HOST
        - name: CLICKHOUSE_HTTP_PORT
          valueFrom:
            configMapKeyRef:
              name: spark-job-config
              key: CLICKHOUSE_HTTP_PORT
        - name: CLICKHOUSE_DB
          valueFrom:
            configMapKeyRef:
              name: spark-job-config
              key: CLICKHOUSE_DB
        - name: CLICKHOUSE_USER
          valueFrom:
            configMapKeyRef:
              name: spark-job-config
              key: CLICKHOUSE_USER
        - name: CLICKHOUSE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: spark-job-secrets
              key: CLICKHOUSE_PASSWORD