apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-job-config
  namespace: spark-jobs
data:
  PYTHONPATH: /opt/project
  POSTGRES_HOST: "host.minikube.internal"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "ecommerce"
  POSTGRES_USER: "tadzhnahal"
  CLICKHOUSE_HOST: "host.minikube.internal"
  CLICKHOUSE_HTTP_PORT: "8123"
  CLICKHOUSE_DB: "analytics"
  CLICKHOUSE_USER: "tadzhnahal"